-- AlterTable
ALTER TABLE `player` ADD COLUMN `def` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `dex` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `dmgMax` INTEGER NOT NULL DEFAULT 5,
    ADD COLUMN `dmgMin` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `hp` INTEGER NOT NULL DEFAULT 50,
    ADD COLUMN `hpMax` INTEGER NOT NULL DEFAULT 50,
    ADD COLUMN `init` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `level` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `pa` INTEGER NOT NULL DEFAULT 20,
    ADD COLUMN `paMax` INTEGER NOT NULL DEFAULT 20,
    ADD COLUMN `str` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `type` VARCHAR(191) NOT NULL DEFAULT 'player',
    ADD COLUMN `xp` INTEGER NOT NULL DEFAULT 0;
